### ISSUE TITLE
Failed test for Emap2sec

### ISSUE THREAD

**Issue by Javad228** [scipion-em/scipion-em-kiharalab#38]
```
Protocol has validation errors:
*Contour: * should be a float
```

I get this error when I run the test_emap2sec. There are no problems during installation. This error repeats for tests TestEmap2sec.test2Emap2secPlus and TestEmap2sec.test3Emap2secPlus.

**Comment by MartinSalinas98** [comment]
Hi @Javad228, thanks for reporting this, and sorry for the late reply, i just saw this issue.

I'll take a look at it today if I can, hopefully it won't be hard to fix.

**Comment by MartinSalinas98** [comment]
I have fixed the issue (I think, I don't have access to a local machine to test there and be 100% sure yet) in #40.

While doing that, I found some extra improvements that could be made to the repository to improve the maintainability, and will implement them in a separate Pull Request.

There is a possibility that, due to potential changes on external dependencies some other tests might not work. I will investigate this when I have a bit more availability to do so, but let me know if you find any further issues.
